"use client"

import { useState } from "react"
import ChannelCard from "@/components/channel-card"
import SummaryBar from "@/components/summary-bar"

const TRIBES_AND_REGIONS = [
  { id: "tangkhul", name: "Tangkhul", region: "Manipur" },
  { id: "naga", name: "Naga", region: "Nagaland" },
  { id: "khasi", name: "Khasi", region: "Meghalaya" },
  { id: "garo", name: "Garo", region: "Meghalaya" },
  { id: "meitei", name: "Meitei", region: "Manipur" },
  { id: "assamese", name: "Assamese", region: "Assam" },
  { id: "manipuri", name: "Manipuri", region: "Manipur" },
  { id: "tripuri", name: "Tripuri", region: "Tripura" },
]

const MOCK_CHANNELS_BY_TRIBE = {
  tangkhul: [
    {
      id: 1,
      channel_name: "Tangkhul Vloggers",
      subscribers: 1200000,
      views: 45000000,
      thumbnail_url: "/tech-channel-logo.png",
      rank: 1,
    },
    {
      id: 2,
      channel_name: "Tangkhul Culture",
      subscribers: 980000,
      views: 38000000,
      thumbnail_url: "/digital-marketing-channel.jpg",
      rank: 2,
    },
    {
      id: 3,
      channel_name: "Tangkhul Music",
      subscribers: 850000,
      views: 32000000,
      thumbnail_url: "/creative-design-channel.jpg",
      rank: 3,
    },
    {
      id: 4,
      channel_name: "Tangkhul Stories",
      subscribers: 750000,
      views: 28000000,
      thumbnail_url: "/business-channel.jpg",
      rank: 4,
    },
    {
      id: 5,
      channel_name: "Tangkhul Entertainment",
      subscribers: 1500000,
      views: 52000000,
      thumbnail_url: "/entertainment-channel.jpg",
      rank: 5,
    },
    {
      id: 6,
      channel_name: "Tangkhul Learning",
      subscribers: 680000,
      views: 25000000,
      thumbnail_url: "/education-channel.jpg",
      rank: 6,
    },
    {
      id: 7,
      channel_name: "Tangkhul Lifestyle",
      subscribers: 920000,
      views: 35000000,
      thumbnail_url: "/lifestyle-vlog-channel.jpg",
      rank: 7,
    },
    {
      id: 8,
      channel_name: "Tangkhul Gaming",
      subscribers: 1100000,
      views: 42000000,
      thumbnail_url: "/gaming-channel.jpg",
      rank: 8,
    },
    {
      id: 9,
      channel_name: "Tangkhul Music Beats",
      subscribers: 1300000,
      views: 48000000,
      thumbnail_url: "/music-channel.png",
      rank: 9,
    },
    {
      id: 10,
      channel_name: "Tangkhul News",
      subscribers: 2100000,
      views: 65000000,
      thumbnail_url: "/news-channel.png",
      rank: 10,
    },
    {
      id: 11,
      channel_name: "Tangkhul Sports",
      subscribers: 1800000,
      views: 55000000,
      thumbnail_url: "/sports-channel.jpg",
      rank: 11,
    },
    {
      id: 12,
      channel_name: "Tangkhul Cooking",
      subscribers: 890000,
      views: 33000000,
      thumbnail_url: "/cooking-channel.jpg",
      rank: 12,
    },
    {
      id: 13,
      channel_name: "Tangkhul Travel",
      subscribers: 760000,
      views: 29000000,
      thumbnail_url: "/travel-channel.jpg",
      rank: 13,
    },
    {
      id: 14,
      channel_name: "Tangkhul Fashion",
      subscribers: 1050000,
      views: 40000000,
      thumbnail_url: "/fashion-channel.jpg",
      rank: 14,
    },
    {
      id: 15,
      channel_name: "Tangkhul Tech",
      subscribers: 1400000,
      views: 50000000,
      thumbnail_url: "/tech-review-channel.jpg",
      rank: 15,
    },
    {
      id: 16,
      channel_name: "Tangkhul Fitness",
      subscribers: 650000,
      views: 24000000,
      thumbnail_url: "/fitness-channel.jpg",
      rank: 16,
    },
    {
      id: 17,
      channel_name: "Tangkhul Movies",
      subscribers: 920000,
      views: 36000000,
      thumbnail_url: "/movie-review-channel.jpg",
      rank: 17,
    },
    {
      id: 18,
      channel_name: "Tangkhul DIY",
      subscribers: 780000,
      views: 30000000,
      thumbnail_url: "/diy-projects-channel.jpg",
      rank: 18,
    },
    {
      id: 19,
      channel_name: "Tangkhul Photography",
      subscribers: 620000,
      views: 23000000,
      thumbnail_url: "/photography-channel.jpg",
      rank: 19,
    },
    {
      id: 20,
      channel_name: "Tangkhul Podcast",
      subscribers: 540000,
      views: 20000000,
      thumbnail_url: "/podcast-channel.jpg",
      rank: 20,
    },
  ],
  naga: [
    {
      id: 21,
      channel_name: "Naga Vloggers",
      subscribers: 1100000,
      views: 42000000,
      thumbnail_url: "/tech-channel-logo.png",
      rank: 1,
    },
    {
      id: 22,
      channel_name: "Naga Culture Hub",
      subscribers: 950000,
      views: 36000000,
      thumbnail_url: "/digital-marketing-channel.jpg",
      rank: 2,
    },
    {
      id: 23,
      channel_name: "Naga Music",
      subscribers: 820000,
      views: 31000000,
      thumbnail_url: "/creative-design-channel.jpg",
      rank: 3,
    },
    {
      id: 24,
      channel_name: "Naga Stories",
      subscribers: 720000,
      views: 27000000,
      thumbnail_url: "/business-channel.jpg",
      rank: 4,
    },
    {
      id: 25,
      channel_name: "Naga Entertainment",
      subscribers: 1400000,
      views: 50000000,
      thumbnail_url: "/entertainment-channel.jpg",
      rank: 5,
    },
    {
      id: 26,
      channel_name: "Naga Learning",
      subscribers: 650000,
      views: 24000000,
      thumbnail_url: "/education-channel.jpg",
      rank: 6,
    },
    {
      id: 27,
      channel_name: "Naga Lifestyle",
      subscribers: 890000,
      views: 34000000,
      thumbnail_url: "/lifestyle-vlog-channel.jpg",
      rank: 7,
    },
    {
      id: 28,
      channel_name: "Naga Gaming",
      subscribers: 1050000,
      views: 40000000,
      thumbnail_url: "/gaming-channel.jpg",
      rank: 8,
    },
    {
      id: 29,
      channel_name: "Naga Music Beats",
      subscribers: 1250000,
      views: 46000000,
      thumbnail_url: "/music-channel.png",
      rank: 9,
    },
    {
      id: 30,
      channel_name: "Naga News",
      subscribers: 2000000,
      views: 62000000,
      thumbnail_url: "/news-channel.png",
      rank: 10,
    },
    {
      id: 31,
      channel_name: "Naga Sports",
      subscribers: 1700000,
      views: 52000000,
      thumbnail_url: "/sports-channel.jpg",
      rank: 11,
    },
    {
      id: 32,
      channel_name: "Naga Cooking",
      subscribers: 860000,
      views: 32000000,
      thumbnail_url: "/cooking-channel.jpg",
      rank: 12,
    },
    {
      id: 33,
      channel_name: "Naga Travel",
      subscribers: 730000,
      views: 28000000,
      thumbnail_url: "/travel-channel.jpg",
      rank: 13,
    },
    {
      id: 34,
      channel_name: "Naga Fashion",
      subscribers: 1020000,
      views: 39000000,
      thumbnail_url: "/fashion-channel.jpg",
      rank: 14,
    },
    {
      id: 35,
      channel_name: "Naga Tech",
      subscribers: 1350000,
      views: 48000000,
      thumbnail_url: "/tech-review-channel.jpg",
      rank: 15,
    },
    {
      id: 36,
      channel_name: "Naga Fitness",
      subscribers: 620000,
      views: 23000000,
      thumbnail_url: "/fitness-channel.jpg",
      rank: 16,
    },
    {
      id: 37,
      channel_name: "Naga Movies",
      subscribers: 890000,
      views: 35000000,
      thumbnail_url: "/movie-review-channel.jpg",
      rank: 17,
    },
    {
      id: 38,
      channel_name: "Naga DIY",
      subscribers: 750000,
      views: 29000000,
      thumbnail_url: "/diy-projects-channel.jpg",
      rank: 18,
    },
    {
      id: 39,
      channel_name: "Naga Photography",
      subscribers: 590000,
      views: 22000000,
      thumbnail_url: "/photography-channel.jpg",
      rank: 19,
    },
    {
      id: 40,
      channel_name: "Naga Podcast",
      subscribers: 510000,
      views: 19000000,
      thumbnail_url: "/podcast-channel.jpg",
      rank: 20,
    },
  ],
  khasi: [
    {
      id: 41,
      channel_name: "Khasi Vloggers",
      subscribers: 950000,
      views: 38000000,
      thumbnail_url: "/tech-channel-logo.png",
      rank: 1,
    },
    {
      id: 42,
      channel_name: "Khasi Culture",
      subscribers: 820000,
      views: 31000000,
      thumbnail_url: "/digital-marketing-channel.jpg",
      rank: 2,
    },
    {
      id: 43,
      channel_name: "Khasi Music",
      subscribers: 750000,
      views: 28000000,
      thumbnail_url: "/creative-design-channel.jpg",
      rank: 3,
    },
    {
      id: 44,
      channel_name: "Khasi Stories",
      subscribers: 680000,
      views: 25000000,
      thumbnail_url: "/business-channel.jpg",
      rank: 4,
    },
    {
      id: 45,
      channel_name: "Khasi Entertainment",
      subscribers: 1300000,
      views: 48000000,
      thumbnail_url: "/entertainment-channel.jpg",
      rank: 5,
    },
    {
      id: 46,
      channel_name: "Khasi Learning",
      subscribers: 600000,
      views: 22000000,
      thumbnail_url: "/education-channel.jpg",
      rank: 6,
    },
    {
      id: 47,
      channel_name: "Khasi Lifestyle",
      subscribers: 820000,
      views: 31000000,
      thumbnail_url: "/lifestyle-vlog-channel.jpg",
      rank: 7,
    },
    {
      id: 48,
      channel_name: "Khasi Gaming",
      subscribers: 950000,
      views: 36000000,
      thumbnail_url: "/gaming-channel.jpg",
      rank: 8,
    },
    {
      id: 49,
      channel_name: "Khasi Music Beats",
      subscribers: 1150000,
      views: 44000000,
      thumbnail_url: "/music-channel.png",
      rank: 9,
    },
    {
      id: 50,
      channel_name: "Khasi News",
      subscribers: 1900000,
      views: 60000000,
      thumbnail_url: "/news-channel.png",
      rank: 10,
    },
    {
      id: 51,
      channel_name: "Khasi Sports",
      subscribers: 1600000,
      views: 50000000,
      thumbnail_url: "/sports-channel.jpg",
      rank: 11,
    },
    {
      id: 52,
      channel_name: "Khasi Cooking",
      subscribers: 800000,
      views: 30000000,
      thumbnail_url: "/cooking-channel.jpg",
      rank: 12,
    },
    {
      id: 53,
      channel_name: "Khasi Travel",
      subscribers: 680000,
      views: 26000000,
      thumbnail_url: "/travel-channel.jpg",
      rank: 13,
    },
    {
      id: 54,
      channel_name: "Khasi Fashion",
      subscribers: 950000,
      views: 36000000,
      thumbnail_url: "/fashion-channel.jpg",
      rank: 14,
    },
    {
      id: 55,
      channel_name: "Khasi Tech",
      subscribers: 1250000,
      views: 46000000,
      thumbnail_url: "/tech-review-channel.jpg",
      rank: 15,
    },
    {
      id: 56,
      channel_name: "Khasi Fitness",
      subscribers: 570000,
      views: 21000000,
      thumbnail_url: "/fitness-channel.jpg",
      rank: 16,
    },
    {
      id: 57,
      channel_name: "Khasi Movies",
      subscribers: 820000,
      views: 31000000,
      thumbnail_url: "/movie-review-channel.jpg",
      rank: 17,
    },
    {
      id: 58,
      channel_name: "Khasi DIY",
      subscribers: 700000,
      views: 27000000,
      thumbnail_url: "/diy-projects-channel.jpg",
      rank: 18,
    },
    {
      id: 59,
      channel_name: "Khasi Photography",
      subscribers: 550000,
      views: 20000000,
      thumbnail_url: "/photography-channel.jpg",
      rank: 19,
    },
    {
      id: 60,
      channel_name: "Khasi Podcast",
      subscribers: 480000,
      views: 18000000,
      thumbnail_url: "/podcast-channel.jpg",
      rank: 20,
    },
  ],
  garo: [
    {
      id: 61,
      channel_name: "Garo Vloggers",
      subscribers: 880000,
      views: 35000000,
      thumbnail_url: "/tech-channel-logo.png",
      rank: 1,
    },
    {
      id: 62,
      channel_name: "Garo Culture",
      subscribers: 750000,
      views: 28000000,
      thumbnail_url: "/digital-marketing-channel.jpg",
      rank: 2,
    },
    {
      id: 63,
      channel_name: "Garo Music",
      subscribers: 680000,
      views: 25000000,
      thumbnail_url: "/creative-design-channel.jpg",
      rank: 3,
    },
    {
      id: 64,
      channel_name: "Garo Stories",
      subscribers: 620000,
      views: 23000000,
      thumbnail_url: "/business-channel.jpg",
      rank: 4,
    },
    {
      id: 65,
      channel_name: "Garo Entertainment",
      subscribers: 1200000,
      views: 45000000,
      thumbnail_url: "/entertainment-channel.jpg",
      rank: 5,
    },
    {
      id: 66,
      channel_name: "Garo Learning",
      subscribers: 550000,
      views: 20000000,
      thumbnail_url: "/education-channel.jpg",
      rank: 6,
    },
    {
      id: 67,
      channel_name: "Garo Lifestyle",
      subscribers: 750000,
      views: 28000000,
      thumbnail_url: "/lifestyle-vlog-channel.jpg",
      rank: 7,
    },
    {
      id: 68,
      channel_name: "Garo Gaming",
      subscribers: 880000,
      views: 33000000,
      thumbnail_url: "/gaming-channel.jpg",
      rank: 8,
    },
    {
      id: 69,
      channel_name: "Garo Music Beats",
      subscribers: 1050000,
      views: 40000000,
      thumbnail_url: "/music-channel.png",
      rank: 9,
    },
    {
      id: 70,
      channel_name: "Garo News",
      subscribers: 1750000,
      views: 55000000,
      thumbnail_url: "/news-channel.png",
      rank: 10,
    },
    {
      id: 71,
      channel_name: "Garo Sports",
      subscribers: 1500000,
      views: 48000000,
      thumbnail_url: "/sports-channel.jpg",
      rank: 11,
    },
    {
      id: 72,
      channel_name: "Garo Cooking",
      subscribers: 750000,
      views: 28000000,
      thumbnail_url: "/cooking-channel.jpg",
      rank: 12,
    },
    {
      id: 73,
      channel_name: "Garo Travel",
      subscribers: 620000,
      views: 23000000,
      thumbnail_url: "/travel-channel.jpg",
      rank: 13,
    },
    {
      id: 74,
      channel_name: "Garo Fashion",
      subscribers: 880000,
      views: 33000000,
      thumbnail_url: "/fashion-channel.jpg",
      rank: 14,
    },
    {
      id: 75,
      channel_name: "Garo Tech",
      subscribers: 1150000,
      views: 44000000,
      thumbnail_url: "/tech-review-channel.jpg",
      rank: 15,
    },
    {
      id: 76,
      channel_name: "Garo Fitness",
      subscribers: 520000,
      views: 19000000,
      thumbnail_url: "/fitness-channel.jpg",
      rank: 16,
    },
    {
      id: 77,
      channel_name: "Garo Movies",
      subscribers: 750000,
      views: 28000000,
      thumbnail_url: "/movie-review-channel.jpg",
      rank: 17,
    },
    {
      id: 78,
      channel_name: "Garo DIY",
      subscribers: 650000,
      views: 24000000,
      thumbnail_url: "/diy-projects-channel.jpg",
      rank: 18,
    },
    {
      id: 79,
      channel_name: "Garo Photography",
      subscribers: 500000,
      views: 18000000,
      thumbnail_url: "/photography-channel.jpg",
      rank: 19,
    },
    {
      id: 80,
      channel_name: "Garo Podcast",
      subscribers: 450000,
      views: 17000000,
      thumbnail_url: "/podcast-channel.jpg",
      rank: 20,
    },
  ],
  meitei: [
    {
      id: 81,
      channel_name: "Meitei Vloggers",
      subscribers: 1050000,
      views: 40000000,
      thumbnail_url: "/tech-channel-logo.png",
      rank: 1,
    },
    {
      id: 82,
      channel_name: "Meitei Culture",
      subscribers: 900000,
      views: 34000000,
      thumbnail_url: "/digital-marketing-channel.jpg",
      rank: 2,
    },
    {
      id: 83,
      channel_name: "Meitei Music",
      subscribers: 800000,
      views: 30000000,
      thumbnail_url: "/creative-design-channel.jpg",
      rank: 3,
    },
    {
      id: 84,
      channel_name: "Meitei Stories",
      subscribers: 700000,
      views: 26000000,
      thumbnail_url: "/business-channel.jpg",
      rank: 4,
    },
    {
      id: 85,
      channel_name: "Meitei Entertainment",
      subscribers: 1350000,
      views: 50000000,
      thumbnail_url: "/entertainment-channel.jpg",
      rank: 5,
    },
    {
      id: 86,
      channel_name: "Meitei Learning",
      subscribers: 620000,
      views: 23000000,
      thumbnail_url: "/education-channel.jpg",
      rank: 6,
    },
    {
      id: 87,
      channel_name: "Meitei Lifestyle",
      subscribers: 880000,
      views: 33000000,
      thumbnail_url: "/lifestyle-vlog-channel.jpg",
      rank: 7,
    },
    {
      id: 88,
      channel_name: "Meitei Gaming",
      subscribers: 1020000,
      views: 38000000,
      thumbnail_url: "/gaming-channel.jpg",
      rank: 8,
    },
    {
      id: 89,
      channel_name: "Meitei Music Beats",
      subscribers: 1200000,
      views: 45000000,
      thumbnail_url: "/music-channel.png",
      rank: 9,
    },
    {
      id: 90,
      channel_name: "Meitei News",
      subscribers: 1950000,
      views: 61000000,
      thumbnail_url: "/news-channel.png",
      rank: 10,
    },
    {
      id: 91,
      channel_name: "Meitei Sports",
      subscribers: 1650000,
      views: 51000000,
      thumbnail_url: "/sports-channel.jpg",
      rank: 11,
    },
    {
      id: 92,
      channel_name: "Meitei Cooking",
      subscribers: 820000,
      views: 31000000,
      thumbnail_url: "/cooking-channel.jpg",
      rank: 12,
    },
    {
      id: 93,
      channel_name: "Meitei Travel",
      subscribers: 700000,
      views: 26000000,
      thumbnail_url: "/travel-channel.jpg",
      rank: 13,
    },
    {
      id: 94,
      channel_name: "Meitei Fashion",
      subscribers: 1000000,
      views: 38000000,
      thumbnail_url: "/fashion-channel.jpg",
      rank: 14,
    },
    {
      id: 95,
      channel_name: "Meitei Tech",
      subscribers: 1300000,
      views: 47000000,
      thumbnail_url: "/tech-review-channel.jpg",
      rank: 15,
    },
    {
      id: 96,
      channel_name: "Meitei Fitness",
      subscribers: 600000,
      views: 22000000,
      thumbnail_url: "/fitness-channel.jpg",
      rank: 16,
    },
    {
      id: 97,
      channel_name: "Meitei Movies",
      subscribers: 880000,
      views: 33000000,
      thumbnail_url: "/movie-review-channel.jpg",
      rank: 17,
    },
    {
      id: 98,
      channel_name: "Meitei DIY",
      subscribers: 720000,
      views: 27000000,
      thumbnail_url: "/diy-projects-channel.jpg",
      rank: 18,
    },
    {
      id: 99,
      channel_name: "Meitei Photography",
      subscribers: 570000,
      views: 21000000,
      thumbnail_url: "/photography-channel.jpg",
      rank: 19,
    },
    {
      id: 100,
      channel_name: "Meitei Podcast",
      subscribers: 500000,
      views: 18000000,
      thumbnail_url: "/podcast-channel.jpg",
      rank: 20,
    },
  ],
  assamese: [
    {
      id: 101,
      channel_name: "Assamese Vloggers",
      subscribers: 920000,
      views: 36000000,
      thumbnail_url: "/tech-channel-logo.png",
      rank: 1,
    },
    {
      id: 102,
      channel_name: "Assamese Culture",
      subscribers: 800000,
      views: 30000000,
      thumbnail_url: "/digital-marketing-channel.jpg",
      rank: 2,
    },
    {
      id: 103,
      channel_name: "Assamese Music",
      subscribers: 720000,
      views: 27000000,
      thumbnail_url: "/creative-design-channel.jpg",
      rank: 3,
    },
    {
      id: 104,
      channel_name: "Assamese Stories",
      subscribers: 650000,
      views: 24000000,
      thumbnail_url: "/business-channel.jpg",
      rank: 4,
    },
    {
      id: 105,
      channel_name: "Assamese Entertainment",
      subscribers: 1250000,
      views: 46000000,
      thumbnail_url: "/entertainment-channel.jpg",
      rank: 5,
    },
    {
      id: 106,
      channel_name: "Assamese Learning",
      subscribers: 580000,
      views: 21000000,
      thumbnail_url: "/education-channel.jpg",
      rank: 6,
    },
    {
      id: 107,
      channel_name: "Assamese Lifestyle",
      subscribers: 800000,
      views: 30000000,
      thumbnail_url: "/lifestyle-vlog-channel.jpg",
      rank: 7,
    },
    {
      id: 108,
      channel_name: "Assamese Gaming",
      subscribers: 920000,
      views: 35000000,
      thumbnail_url: "/gaming-channel.jpg",
      rank: 8,
    },
    {
      id: 109,
      channel_name: "Assamese Music Beats",
      subscribers: 1100000,
      views: 42000000,
      thumbnail_url: "/music-channel.png",
      rank: 9,
    },
    {
      id: 110,
      channel_name: "Assamese News",
      subscribers: 1850000,
      views: 58000000,
      thumbnail_url: "/news-channel.png",
      rank: 10,
    },
    {
      id: 111,
      channel_name: "Assamese Sports",
      subscribers: 1550000,
      views: 49000000,
      thumbnail_url: "/sports-channel.jpg",
      rank: 11,
    },
    {
      id: 112,
      channel_name: "Assamese Cooking",
      subscribers: 780000,
      views: 29000000,
      thumbnail_url: "/cooking-channel.jpg",
      rank: 12,
    },
    {
      id: 113,
      channel_name: "Assamese Travel",
      subscribers: 650000,
      views: 24000000,
      thumbnail_url: "/travel-channel.jpg",
      rank: 13,
    },
    {
      id: 114,
      channel_name: "Assamese Fashion",
      subscribers: 920000,
      views: 35000000,
      thumbnail_url: "/fashion-channel.jpg",
      rank: 14,
    },
    {
      id: 115,
      channel_name: "Assamese Tech",
      subscribers: 1200000,
      views: 45000000,
      thumbnail_url: "/tech-review-channel.jpg",
      rank: 15,
    },
    {
      id: 116,
      channel_name: "Assamese Fitness",
      subscribers: 550000,
      views: 20000000,
      thumbnail_url: "/fitness-channel.jpg",
      rank: 16,
    },
    {
      id: 117,
      channel_name: "Assamese Movies",
      subscribers: 800000,
      views: 30000000,
      thumbnail_url: "/movie-review-channel.jpg",
      rank: 17,
    },
    {
      id: 118,
      channel_name: "Assamese DIY",
      subscribers: 680000,
      views: 25000000,
      thumbnail_url: "/diy-projects-channel.jpg",
      rank: 18,
    },
    {
      id: 119,
      channel_name: "Assamese Photography",
      subscribers: 530000,
      views: 19000000,
      thumbnail_url: "/photography-channel.jpg",
      rank: 19,
    },
    {
      id: 120,
      channel_name: "Assamese Podcast",
      subscribers: 470000,
      views: 17000000,
      thumbnail_url: "/podcast-channel.jpg",
      rank: 20,
    },
  ],
  manipuri: [
    {
      id: 121,
      channel_name: "Manipuri Vloggers",
      subscribers: 1000000,
      views: 38000000,
      thumbnail_url: "/tech-channel-logo.png",
      rank: 1,
    },
    {
      id: 122,
      channel_name: "Manipuri Culture",
      subscribers: 850000,
      views: 32000000,
      thumbnail_url: "/digital-marketing-channel.jpg",
      rank: 2,
    },
    {
      id: 123,
      channel_name: "Manipuri Music",
      subscribers: 780000,
      views: 29000000,
      thumbnail_url: "/creative-design-channel.jpg",
      rank: 3,
    },
    {
      id: 124,
      channel_name: "Manipuri Stories",
      subscribers: 680000,
      views: 25000000,
      thumbnail_url: "/business-channel.jpg",
      rank: 4,
    },
    {
      id: 125,
      channel_name: "Manipuri Entertainment",
      subscribers: 1300000,
      views: 48000000,
      thumbnail_url: "/entertainment-channel.jpg",
      rank: 5,
    },
    {
      id: 126,
      channel_name: "Manipuri Learning",
      subscribers: 600000,
      views: 22000000,
      thumbnail_url: "/education-channel.jpg",
      rank: 6,
    },
    {
      id: 127,
      channel_name: "Manipuri Lifestyle",
      subscribers: 850000,
      views: 32000000,
      thumbnail_url: "/lifestyle-vlog-channel.jpg",
      rank: 7,
    },
    {
      id: 128,
      channel_name: "Manipuri Gaming",
      subscribers: 980000,
      views: 37000000,
      thumbnail_url: "/gaming-channel.jpg",
      rank: 8,
    },
    {
      id: 129,
      channel_name: "Manipuri Music Beats",
      subscribers: 1150000,
      views: 43000000,
      thumbnail_url: "/music-channel.png",
      rank: 9,
    },
    {
      id: 130,
      channel_name: "Manipuri News",
      subscribers: 1900000,
      views: 59000000,
      thumbnail_url: "/news-channel.png",
      rank: 10,
    },
    {
      id: 131,
      channel_name: "Manipuri Sports",
      subscribers: 1600000,
      views: 50000000,
      thumbnail_url: "/sports-channel.jpg",
      rank: 11,
    },
    {
      id: 132,
      channel_name: "Manipuri Cooking",
      subscribers: 800000,
      views: 30000000,
      thumbnail_url: "/cooking-channel.jpg",
      rank: 12,
    },
    {
      id: 133,
      channel_name: "Manipuri Travel",
      subscribers: 680000,
      views: 25000000,
      thumbnail_url: "/travel-channel.jpg",
      rank: 13,
    },
    {
      id: 134,
      channel_name: "Manipuri Fashion",
      subscribers: 950000,
      views: 36000000,
      thumbnail_url: "/fashion-channel.jpg",
      rank: 14,
    },
    {
      id: 135,
      channel_name: "Manipuri Tech",
      subscribers: 1250000,
      views: 46000000,
      thumbnail_url: "/tech-review-channel.jpg",
      rank: 15,
    },
    {
      id: 136,
      channel_name: "Manipuri Fitness",
      subscribers: 580000,
      views: 21000000,
      thumbnail_url: "/fitness-channel.jpg",
      rank: 16,
    },
    {
      id: 137,
      channel_name: "Manipuri Movies",
      subscribers: 850000,
      views: 32000000,
      thumbnail_url: "/movie-review-channel.jpg",
      rank: 17,
    },
    {
      id: 138,
      channel_name: "Manipuri DIY",
      subscribers: 700000,
      views: 26000000,
      thumbnail_url: "/diy-projects-channel.jpg",
      rank: 18,
    },
    {
      id: 139,
      channel_name: "Manipuri Photography",
      subscribers: 550000,
      views: 20000000,
      thumbnail_url: "/photography-channel.jpg",
      rank: 19,
    },
    {
      id: 140,
      channel_name: "Manipuri Podcast",
      subscribers: 480000,
      views: 18000000,
      thumbnail_url: "/podcast-channel.jpg",
      rank: 20,
    },
  ],
  tripuri: [
    {
      id: 141,
      channel_name: "Tripuri Vloggers",
      subscribers: 850000,
      views: 32000000,
      thumbnail_url: "/tech-channel-logo.png",
      rank: 1,
    },
    {
      id: 142,
      channel_name: "Tripuri Culture",
      subscribers: 720000,
      views: 27000000,
      thumbnail_url: "/digital-marketing-channel.jpg",
      rank: 2,
    },
    {
      id: 143,
      channel_name: "Tripuri Music",
      subscribers: 650000,
      views: 24000000,
      thumbnail_url: "/creative-design-channel.jpg",
      rank: 3,
    },
    {
      id: 144,
      channel_name: "Tripuri Stories",
      subscribers: 580000,
      views: 21000000,
      thumbnail_url: "/business-channel.jpg",
      rank: 4,
    },
    {
      id: 145,
      channel_name: "Tripuri Entertainment",
      subscribers: 1150000,
      views: 43000000,
      thumbnail_url: "/entertainment-channel.jpg",
      rank: 5,
    },
    {
      id: 146,
      channel_name: "Tripuri Learning",
      subscribers: 520000,
      views: 19000000,
      thumbnail_url: "/education-channel.jpg",
      rank: 6,
    },
    {
      id: 147,
      channel_name: "Tripuri Lifestyle",
      subscribers: 750000,
      views: 28000000,
      thumbnail_url: "/lifestyle-vlog-channel.jpg",
      rank: 7,
    },
    {
      id: 148,
      channel_name: "Tripuri Gaming",
      subscribers: 850000,
      views: 32000000,
      thumbnail_url: "/gaming-channel.jpg",
      rank: 8,
    },
    {
      id: 149,
      channel_name: "Tripuri Music Beats",
      subscribers: 1000000,
      views: 38000000,
      thumbnail_url: "/music-channel.png",
      rank: 9,
    },
    {
      id: 150,
      channel_name: "Tripuri News",
      subscribers: 1700000,
      views: 53000000,
      thumbnail_url: "/news-channel.png",
      rank: 10,
    },
    {
      id: 151,
      channel_name: "Tripuri Sports",
      subscribers: 1450000,
      views: 46000000,
      thumbnail_url: "/sports-channel.jpg",
      rank: 11,
    },
    {
      id: 152,
      channel_name: "Tripuri Cooking",
      subscribers: 720000,
      views: 27000000,
      thumbnail_url: "/cooking-channel.jpg",
      rank: 12,
    },
    {
      id: 153,
      channel_name: "Tripuri Travel",
      subscribers: 600000,
      views: 22000000,
      thumbnail_url: "/travel-channel.jpg",
      rank: 13,
    },
    {
      id: 154,
      channel_name: "Tripuri Fashion",
      subscribers: 850000,
      views: 32000000,
      thumbnail_url: "/fashion-channel.jpg",
      rank: 14,
    },
    {
      id: 155,
      channel_name: "Tripuri Tech",
      subscribers: 1100000,
      views: 41000000,
      thumbnail_url: "/tech-review-channel.jpg",
      rank: 15,
    },
    {
      id: 156,
      channel_name: "Tripuri Fitness",
      subscribers: 500000,
      views: 18000000,
      thumbnail_url: "/fitness-channel.jpg",
      rank: 16,
    },
    {
      id: 157,
      channel_name: "Tripuri Movies",
      subscribers: 750000,
      views: 28000000,
      thumbnail_url: "/movie-review-channel.jpg",
      rank: 17,
    },
    {
      id: 158,
      channel_name: "Tripuri DIY",
      subscribers: 620000,
      views: 23000000,
      thumbnail_url: "/diy-projects-channel.jpg",
      rank: 18,
    },
    {
      id: 159,
      channel_name: "Tripuri Photography",
      subscribers: 480000,
      views: 17000000,
      thumbnail_url: "/photography-channel.jpg",
      rank: 19,
    },
    {
      id: 160,
      channel_name: "Tripuri Podcast",
      subscribers: 420000,
      views: 15000000,
      thumbnail_url: "/podcast-channel.jpg",
      rank: 20,
    },
  ],
}

export default function YouTubeDashboard() {
  const [selectedTribe, setSelectedTribe] = useState(TRIBES_AND_REGIONS[0].id)
  const [sortBy, setSortBy] = useState<"subscribers" | "views">("subscribers")

  const channels = MOCK_CHANNELS_BY_TRIBE[selectedTribe as keyof typeof MOCK_CHANNELS_BY_TRIBE] || []

  const sortedChannels = [...channels].sort((a, b) => {
    if (sortBy === "subscribers") {
      return b.subscribers - a.subscribers
    }
    return b.views - a.views
  })

  const totalSubscribers = sortedChannels.reduce((sum, ch) => sum + ch.subscribers, 0)
  const totalViews = sortedChannels.reduce((sum, ch) => sum + ch.views, 0)

  const currentTribe = TRIBES_AND_REGIONS.find((t) => t.id === selectedTribe)

  return (
    <main className="min-h-screen bg-background">
      {/* Header */}
      <div className="border-b border-border bg-card">
        <div className="mx-auto max-w-7xl px-4 py-8 sm:px-6 lg:px-8">
          <h1 className="text-3xl font-bold text-foreground">YouTube Tribal Top Channels</h1>
          <p className="mt-2 text-muted-foreground">Explore the top-performing YouTube channels by tribe and region</p>
        </div>
      </div>

      {/* Main Content */}
      <div className="mx-auto max-w-7xl px-4 py-8 sm:px-6 lg:px-8">
        {/* Filters */}
        <div className="mb-8 flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
          <div className="flex flex-col gap-2">
            <label className="text-sm font-medium text-foreground">Select Tribe & Region</label>
            <select
              value={selectedTribe}
              onChange={(e) => setSelectedTribe(e.target.value)}
              className="w-full rounded-md border border-input bg-background px-3 py-2 text-foreground sm:w-64"
            >
              {TRIBES_AND_REGIONS.map((tribe) => (
                <option key={tribe.id} value={tribe.id}>
                  {tribe.name} - {tribe.region}
                </option>
              ))}
            </select>
          </div>

          <div className="flex flex-col gap-2">
            <label className="text-sm font-medium text-foreground">Sort By</label>
            <div className="flex gap-2">
              <button
                onClick={() => setSortBy("subscribers")}
                className={`rounded-md px-4 py-2 text-sm font-medium transition-colors ${
                  sortBy === "subscribers"
                    ? "bg-primary text-primary-foreground"
                    : "border border-input bg-background text-foreground hover:bg-muted"
                }`}
              >
                Subscribers
              </button>
              <button
                onClick={() => setSortBy("views")}
                className={`rounded-md px-4 py-2 text-sm font-medium transition-colors ${
                  sortBy === "views"
                    ? "bg-primary text-primary-foreground"
                    : "border border-input bg-background text-foreground hover:bg-muted"
                }`}
              >
                Views
              </button>
            </div>
          </div>
        </div>

        {/* Summary Bar */}
        <SummaryBar totalSubscribers={totalSubscribers} totalViews={totalViews} />

        {/* Tribe Info */}
        <div className="mb-6 rounded-lg border border-border bg-card p-4">
          <p className="text-sm text-muted-foreground">
            Showing top channels for <span className="font-semibold text-foreground">{currentTribe?.name}</span> tribe
            in <span className="font-semibold text-foreground">{currentTribe?.region}</span>
          </p>
        </div>

        {/* Channels Grid */}
        <div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
          {sortedChannels.map((channel) => (
            <ChannelCard key={channel.id} channel={channel} />
          ))}
        </div>
      </div>
    </main>
  )
}
